# To publish the action, follow this:https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace
name: 'Pull Request Status Checks GIF'
description: 'GitHub Action that displays a random thumbs up or thumbs down gif, from Giphy, based on the status of the PR status checks.'
author: 'dgteixeira'
inputs:
  GITHUB_TOKEN:
    description: 'Token for the repository. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
  GIPHY_API_KEY:
    description: 'Your secret Giphy Api Key.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.GIPHY_API_KEY }}
branding:
  icon: 'thumbs-up'
  color: 'gray-dark'